let suggestions = [
    "stejproject.github.io",
    "stejproject",
    "YouTube",
    "Google",
    "Technologies",
    "Discord",
    "Microsoft",
    "Instagram",
    "Classroom",
    "Whatsapp",
    "D-Link",
    "Skynet",
    "Electronics",
    "Canva",
    "https://softmany.com/",
    "Tutorial",
    "site:stackoverflow.com ",
    "site:github.com ",
    "translate",
    "math",
    "physics",
    "chemist",
    "biology",
    "tools",
];